---
# tasks file for yannallandit.rsfo


- name: deploy RSFO (Rapid Setup For Oracle)
  become: yes
  become_user: root
  copy:
    src: files/rsfo-1.1.5-1.el7.noarch.rpm
    dest: /tmp
    owner: root
    group: root
    mode: 0664
    force: true

- name: create scripts directory
  become: yes
  become_user: root
  file:
    path: /tmp/scripts
    state: directory
    mode: 0666

- name: copy answer files
  become: yes
  become_user: root
  copy:
    src: files/rsfoparam.txt
    dest: /tmp/scripts/
    owner: root
    group: root
    mode: 0666

- name: copy nodelist file
  become: yes
  become_user: root
  copy:
    src: files/nod_list.txt
    dest: /tmp/scripts/
    owner: root
    group: root
    mode: 0666

- name: update node list
  become: yes
  become_user: root
  lineinfile:
    dest: /tmp/scripts/nod_list.txt
    regexp: "privnodename1 privnodename2"
    line: "{{ MAIN_NODE }} {{ TARGET_NODES }}"

- name: update RSFO answer file - GRID_BASE
  become: yes
  become_user: root
  lineinfile:
    dest: /tmp/scripts/rsfoparam.txt
    regexp: "GRID_BASE=/u01/app/grid"
    line: "GRID_BASE={{ GRID_BASE }}"

- name: update RSFO answer file - HOME_BASE
  become: yes
  become_user: root
  lineinfile:
    dest: /tmp/scripts/rsfoparam.txt
    regexp: "ORA_BASE=/u02/app/oracle"
    line: "ORA_BASE={{ ORA_BASE }}"

- name: Install RSFO package
  become: yes
  become_user: root
  yum:
    name: /tmp/rsfo-1.1.5-1.el7.noarch.rpm
    state: present

- name: Run RSFO OS Setting script
  become: yes
  become_user: root
  shell: /opt/hpe/rsfo/rsfo_run1_os7up.sh >> /tmp/scripts/rsfo_run1_os7up.log

- name: Run RSFO Oracle Setting script
  become: yes
  become_user: root
  shell: /opt/hpe/rsfo/rsfo_run2_cruser.sh >> /tmp/scripts/rsfo_run2_cruser.log

- name: Print end message
  debug:
    msg: "Look at the installation logs in {{ MAIN_NODE }}:/tmp/scripts"
